update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,6 +13,7 @@ env:
   IMAGE: 875285643684.dkr.ecr.us-east-1.amazonaws.com/flaskapp-simple-bank
   REGION: us-east-1
   S3_BUCKET: s3://875285643684-devops-scripts
+  ECR: 875285643684.dkr.ecr.us-east-1.amazonaws.com
 
 jobs:
   build-and-deploy:
@@ -31,8 +32,7 @@ jobs:
       - name: Login to ECR
         run: |
           aws ecr get-login-password --region ${{ env.REGION }} | \
-          docker login --username AWS --password-stdin \
-          875285643684.dkr.ecr.${{ env.REGION }}.amazonaws.com
+          docker login --username AWS --password-stdin ${{env.ECR}}
           echo "Login Successfull to ECR ✅"
 
       - name: Build and Push image
@@ -45,8 +45,70 @@ jobs:
           docker push ${{env.IMAGE}}:latest
           echo "Image Pushed : ${{env.VERSION}} ✅"
 
-      - name: Upload Docker-Compose to  
+      - name: Upload Docker-Compose to S3 
         run: |
           aws s3 mb ${{ env.S3_BUCKET }} --region ${{ env.REGION }} 2>/dev/null || true
           aws s3 cp docker-compose.yml ${{ env.S3_BUCKET }}/docker-compose.yml --region ${{ env.REGION }}
           echo "Docker compose Uploaded ✅"
+
+      - name: Deploy via SSM
+        run: |
+          CMD_ID=$(aws ssm send-command \
+          --target "Key=tag:App,Values=flask" \
+          --document-name "AWS-RunShellScript" \
+          --comment "Deploy ${{ env.VERSION }} by ${{ github.actor }}" \
+          --parameters '{"command":[
+            "set -e"
+            "aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.ECR }}",
+              "mkdir -p /home/ubuntu/app",
+              "aws s3 cp ${{ env.S3_BUCKET }}/docker-compose.yml /home/ubuntu/app/docker-compose.yml",
+              "docker pull ${{ env.IMAGE }}:${{ env.VERSION }}",
+              "docker stop simplebank 2>/dev/null  true",
+              "docker rm simplebank 2>/dev/null  true",
+              "cd /home/ubuntu/app && IMAGE_TAG=${{ env.VERSION }} docker compose up -d",
+              "docker ps --filter name=simplebank --format {{.Status}} | grep -q Up && echo CONTAINER_RUNNING  (echo CONTAINER_FAILED && exit 1)"
+            ]}' \
+            --query 'Command.CommandId' \
+            --output text \
+            --region ${{ env.REGION }})
+
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
+
+      - name: Verify Deployment
+        run: |
+          for i in {1..10}; do
+            STATUS=$(aws ssm list-command-invocations \
+              --command-id "${{ steps.deploy.outputs.cmd_id }}" \
+              --query "CommandInvocations[*].Status" \
+              --output text \
+              --region ${{ env.REGION }})
+
+            echo "[$i] Status: $STATUS"
+            echo "$STATUS" | grep -q "InProgress\|Pending" && sleep 10  break
+          done
+
+          echo "============ DEPLOY RESULTS ============"
+
+          aws ssm list-command-invocations \
+            --command-id "${{ steps.deploy.outputs.cmd_id }}" \
+            --details \
+            --region ${{ env.REGION }} \
+            --query "CommandInvocations[*].[InstanceId,Status,CommandPlugins[0].Output]" \
+            --output text | while IFS=$'\t' read -r instance status output; do
+              echo "Instance : $instance"
+              echo "Status   : $status"
+              echo "$output" | tail -5
+              echo "----------------------------------------"
+            done
+
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.deploy.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region ${{ env.REGION }})
+
+          [ "$FAILED" -gt 0 ] && \
+            echo "::error::Deploy failed on $FAILED instance(s)!" && \
+            exit 1
+
+          echo "✅ Deploy successful — ${{ env.VERSION }}"
